### PR TITLE
fix: Handle error on channel receive

### LINKED ISSUE #1646: tx_user_feed stops broadcasting new logins
It appears we are stopping to process new logins every now and then. Although we continue to log `New login` on our websocket, the corresponding `NewUser` event does not get broadcasted.

This ends up that we do not check if there are any pending tasks for the user on login, e.g. collab revert, expired positions or rollover.

The issue can be resolved after a restart.

### PR DESCRIPTION
**Pull request by holzeis**
Without that fixed we would have simply broke out of the loop and the task completed.

Note, the capacity of a 100 should have been enough, and it doesn't look like the channel got closed. Hopefully we learn more by logging errors when receiving a message from the channel.

fixes #1646

### CODE REVIEW

File: coordinator/src/message.rs [hunk 1]
```diff
@@ -48,10 +49,21 @@ pub fn spawn_delivering_messages_to_authenticated_users(
...
+                match user_feed.recv().await {
+                    Ok(new_user_msg) => {
+                        traders
+                            .write()
+                            .insert(new_user_msg.new_user, new_user_msg.sender);
+                    }
+                    Err(RecvError::Closed) => {
+                        tracing::error!("New user message sender died! Channel closed.");
+                        break;
+                    }
```
Comment (bonomat) [inline coordinator/src/message.rs:62]: Eventually we could try to re-subscribe to the channel here.

Comment (holzeis) [reply coordinator/src/message.rs:62]: Even if the sender died? I think resubscribing would only make sense if the sender is also able to restart.

Comment (bonomat) [reply coordinator/src/message.rs:62]: True. Makes sense.
