### PR TITLE
fix: Calculate liquidation price from opposite direction if the position is reduced

### LINKED ISSUE #2403: Liquidation price on resize is calculated wrongly
When resizing the position we get confronted with a confirmation dialog showing 
- margin
- liquidation price
- order matching fee

The liquidation price seems to be based on the new order, not on the updated position

in the screenshot below I had

- 100 long , @ $100k
- then go 50 short @ $100k

Afaik the liquidation price here is based on `50 short @ 100k` and not at the remaining `50 long`

image

### PR DESCRIPTION
**Pull request by holzeis**
fixes #2403 

Additionally I reworked the confirmation screen a bit. Nothing fundamental, but tweaked a little bit what information is shown depending on the corresponding trade action.

https://github.com/get10101/10101/assets/382048/a06b0121-7122-4263-b410-14578368ba0b

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
I didn't thoroughly review the diff, but I love the changes.

File: mobile/lib/features/trade/trade_bottom_sheet_tab.dart [hunk 1]
```diff
@@ -350,8 +350,13 @@ class _TradeBottomSheetTabState extends State<TradeBottomSheetTab>
                     selector: (_, provider) =>
                         provider.fromDirection(direction).liquidationPrice ?? 0.0,
                     builder: (context, liquidationPrice, child) {
-                      return ValueDataRow(
-                          type: ValueType.fiat, value: liquidationPrice, label: "Liquidation:");
+                      if (tradeValues.openQuantity == tradeValues.contracts) {
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_tab.dart:355]: How does it know that this is a close? I mean, wouldn't this also be true if you are `100 long` and then go another `100 long`?

File: mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart [hunk 2]
```diff
@@ -180,6 +167,52 @@ class TradeBottomSheetConfirmation extends StatelessWidget {
         ? Amount((referralStatus.referralFeeBonus * orderMatchingFee.sats).floor())
         : Amount.zero();
 
+    final description = switch (tradeAction) {
+      TradeAction.closePosition => RichText(
+          text: TextSpan(
+              text:
+                  '\nBy confirming, a closing market order will be created. Once the order is matched, your position will be closed.',
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart:176]: _closing_ is redundant as it's mentioned in the second half of the sentence. 

```suggestion
                  '\nBy confirming, a market order will be created. Once the order is matched, your position will be closed.',
```

File: mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart [hunk 3]
```diff
@@ -180,6 +167,52 @@ class TradeBottomSheetConfirmation extends StatelessWidget {
...
+              style: DefaultTextStyle.of(context).style)),
+      TradeAction.openChannel || TradeAction.trade => RichText(
+          text: TextSpan(
+            text: '\nBy confirming, a new order will be created. Once the order is matched, ',
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart:180]:
```suggestion
            text: '\nBy confirming, a market order will be created. Once the order is matched, ',

```

File: mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart [hunk 4]
```diff
@@ -180,6 +167,52 @@ class TradeBottomSheetConfirmation extends StatelessWidget {
...
+            children: <TextSpan>[
+              TextSpan(
+                  text: formatSats(total), style: const TextStyle(fontWeight: FontWeight.bold)),
+              const TextSpan(text: ' will be locked up in a DLC channel!'),
+            ],
+          ),
+        ),
+      TradeAction.reducePosition => RichText(
+          text: TextSpan(
+            text: '\nBy confirming, a new order will be created reducing your position to ',
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart:191]:
```suggestion
            text: '\nBy confirming, a market order will be created reducing your position to ',
```

File: mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart [hunk 5]
```diff
@@ -180,6 +167,52 @@ class TradeBottomSheetConfirmation extends StatelessWidget {
...
+              TextSpan(
+                  text: formatUsd(tradeValues.openQuantity - tradeValues.contracts),
+                  style: const TextStyle(fontWeight: FontWeight.bold)),
+            ],
+          ),
+        ),
+      TradeAction.changeDirection => RichText(
+          text: TextSpan(
+            text:
+                '\nBy confirming, a new order will be created changing the direction of your position to ',
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart:203]:
```suggestion
                '\nBy confirming, a market order will be created changing the direction of your position to ',
```

File: mobile/lib/features/trade/trade_bottom_sheet_tab.dart [hunk 6]
```diff
@@ -395,4 +397,26 @@ class _TradeBottomSheetTabState extends State<TradeBottomSheetTab>
...
   @override
   bool get wantKeepAlive => true;
+
+  /// Returns the trade action depending on the trade values and if a channel exists
+  TradeAction getTradeAction(TradeValues tradeValues, bool hasChannel) {
+    if (!hasChannel) {
+      return TradeAction.openChannel;
+    }
+
+    if (tradeValues.openQuantity == tradeValues.contracts) {
```
Comment (bonomat) [inline mobile/lib/features/trade/trade_bottom_sheet_tab.dart:407]: I feel like I'm missing something, how does it know the direction?

**Review by bonomat — COMMENTED** [review]
I guess it works but I don't understand it. Maybe you can explain how `openQuantity` works?

File: mobile/lib/features/trade/trade_bottom_sheet_tab.dart (hunk 1 above)
Comment (holzeis) [reply mobile/lib/features/trade/trade_bottom_sheet_tab.dart:355]: `openQuantity` is only set for the opposite direction. So if you'd go 100 long and then again 100 long the open quantity would be 0.

It would be 100 for the short direction. So if you'd go 100 short, you'd close the position.

Comment (bonomat) [reply mobile/lib/features/trade/trade_bottom_sheet_tab.dart:355]: oh man, this really needs to be documented somewhere 🙈

Comment (holzeis) [reply mobile/lib/features/trade/trade_bottom_sheet_tab.dart:355]: I will extend the docs on the open quantity field

File: mobile/lib/features/trade/trade_bottom_sheet_tab.dart (hunk 6 above)
Comment (holzeis) [reply mobile/lib/features/trade/trade_bottom_sheet_tab.dart:407]: The open quantity is only set for the opposite direction of the position. so if the user buys/sells as many contracts as they currently have open, the position will be closed.
