### PR TITLE
fix: read scorer

### LINKED ISSUE #797: Panic on reading scorer from disk
My app started to crash after a restart because the scorer file was broken.

xcode://organizer/crashes/downloadPoint?adamId=1671686549&platformId=iOS&installPlatformId=iOS&analyticsPointId=DUp8-dcHhayUiR7pI4Hsm&bundleId=finance.get10101.app

Luckily this can be easily fixed by simply deleting the scorer file.

### PR DESCRIPTION
**Pull request by bonomat**
With this patch we don't read a historically stored scrorer from disk. It's not ideal, but at least users running into panics when loading the scorer will be able to run the app again

Workaround for #797 
fix #797

### CODE REVIEW

File: crates/ln-dlc-node/src/disk.rs [hunk 1]
```diff
@@ -15,13 +15,13 @@ pub(crate) fn read_scorer(
...
 ) -> ProbabilisticScorer<Arc<NetworkGraph>, Arc<TracingLogger>> {
     let params = ProbabilisticScoringParameters::default();
-    if let Ok(file) = File::open(path) {
-        let args = (params.clone(), graph.clone(), logger.clone());
-        match ProbabilisticScorer::read(&mut BufReader::new(file), args) {
-            Ok(scorer) => return scorer,
-            Err(e) => tracing::error!("Failed to read scorer from disk: {e}"),
-        }
-    }
+    // if let Ok(file) = File::open(path) {
```
Comment (holzeis) [inline crates/ln-dlc-node/src/disk.rs:18]: nit: I guess we can remove that commented code and if we need it again we can look at this commit.

**Review by holzeis — APPROVED** [review]
@bonomat great, if that fixes the issue 🙂

As we have checked my scorer file was anyways empty, so I guess it doesn't hurt not reading the file from disk?

Are there any big disadvantages of recreating the scorer from scratch every time?

File: crates/ln-dlc-node/src/disk.rs (hunk 1 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/disk.rs]: I think the second commit is more serious. Unfortunately I can't reproduce the panic anymore :/

**Comment by bonomat** [comment]
> Are there any big disadvantages of recreating the scorer from scratch every time?

I guess we could run without reading from disc. This means, we will not learn from past payments and only keep an in-memory picture of the network.

**Comment by bonomat** [comment]
@reviewers 
1. The first commit fixed the problem for me
2. The second commit might be the better fix but I can't test it because it does not panic anymore. 

If we go for the second, let's squash the commits. 
I propose to roll out a new version with this asap, because you really can't use the app if this happens to you.

**Review by klochowicz — APPROVED** [review]
I would go for solution 2 - it does not panic anymore, and we're logging potential problems, without sweeping them completely under the rug.

**Comment by holzeis** [comment]
> I propose to roll out a new version with this asap, because you really can't use the app if this happens to you.

@bonomat fyi: https://github.com/get10101/10101/actions/runs/5540939930/jobs/10113681545
