### PR TITLE
fix: Store matching fee and trader pnl into trade params

### LINKED ISSUE #2484: Trader realized pnl is not updated on the trade when resizing a position

### PR DESCRIPTION
**Pull request by holzeis**
fixes #2484

### CODE REVIEW

File: coordinator/src/db/trade_params.rs [hunk 1]
```diff
@@ -42,6 +42,8 @@ pub(crate) fn insert(
             trade_params::trader_pubkey.eq(params.trader.to_string()),
             trade_params::direction.eq(Direction::from(params.direction)),
             trade_params::average_price.eq(params.average_price),
+            trade_params::matching_fee.eq(params.matching_fee.to_sat() as i64),
```
Comment (luckysori) [inline coordinator/src/db/trade_params.rs:45]: Oops, I think this was my fault.

We should destructure the `TradeParams` so that the compiler can complain when a new field is missing or not used
