### PR TITLE
Fix rust-lightning log & create all data dirs for on chain wallet

### LINKED ISSUE #103: Configure `rust-lightning` to emit trace logs
This did work in `10101-poc`.

### PR DESCRIPTION
**Pull request by Restioson**
Two commits here
- Create all data dirs for on chain walet: this will create all required parent directories (similar to `mkdir -p`)
- Log rust-lightning records to tracing: this logs records from rust-lightning crates to tracing through the tracing_log crate 

This is a small PR because I can't push to upstream currently. Fixes #103.

### CODE REVIEW

**Comment by Restioson** [comment]
These formatting failures do not come from the files I changed

**Review by holzeis — APPROVED** [review]
Thank you!

File: crates/ln-dlc-node/src/on_chain_wallet.rs [hunk 1]
```diff
@@ -21,8 +21,9 @@ impl OnChainWallet {
         let data_dir = data_dir.join(&network.to_string());
         if !data_dir.exists() {
             // TODO: Had to create the `on_chain` directory manually for this to work in the tests
```
Comment (holzeis) [inline crates/ln-dlc-node/src/on_chain_wallet.rs:23]: nit: we could remove the comment then ;)

Comment (Restioson) [reply crates/ln-dlc-node/src/on_chain_wallet.rs]: Pushed as fixup - let me know when ready for merge and I can squash down

**Comment by Restioson** [comment]
One note; trace and gossip are not currently distinguished from one another and are merged into one log level (trace)

**Review by holzeis — APPROVED** [review]
Looks good, thank you! please squash your fixup and merge! 🙂

**Comment by Restioson** [comment]
Pushed now :)
