### PR TITLE
fix: Wait for outbound capacity before paying jit channel open fee

### LINKED ISSUE #883: Skipping direct route to payee when making payments from app to coordinator
We have seen this problem when testing the app on the public regtest setup.

For instance, when trying to pay the channel-opening fee from app to coordinator this can happen, preventing the app from paying for these costs.

```
| 2023-07-26 18:06:55.383 | LogLevel.DEBUG | Trying to pay channel opening fees of 153  
| 2023-07-26 18:06:55.437 | LogLevel.TRACE | lightning::routing::router: Searching for a route from payer 02a6fec7dfc1c99ec359fb4ee1f413d3de26016fc709ba100ba06daabce2be42cd to payee 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802 with MPP and 1 first hops overriding the network graph  
| 2023-07-26 18:06:55.437 | LogLevel.TRACE | lightning::routing::router: Building path from 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802 (payee) to 02a6fec7dfc1c99ec359fb4ee1f413d3de26016fc709ba100ba06daabce2be42cd (us/payer) for value 153000 msat.  
| 2023-07-26 18:06:55.438 | LogLevel.TRACE | lightning::routing::router: Skipped direct route to payeeSkipped direct route to payee via SCID 1099653251074  
| 2023-07-26 18:06:55.438 | LogLevel.TRACE | lightning::routing::router: Starting main path collection loop with 5 nodes pre-filled from first/last hops.  
| 2023-07-26 18:06:55.439 | LogLevel.TRACE | lightning::routing::router: Skipped direct route to payee via SCID 1099653251074  
| 2023-07-26 18:06:55.440 | LogLevel.TRACE | lightning::routing::router: Starting main path collection loop with 5 nodes pre-filled from first/last hops.  
| 2023-07-26 18:06:55.440 | LogLevel.TRACE | lightning::routing::router: Have now collected 0 msat (seeking 459000 msat) in paths. Last path loop did not find a new path.  
| 2023-07-26 18:06:55.440 | LogLevel.ERROR | Failed to send payment err: RouteNotFound 
| 2023-07-26 18:06:55.441 | LogLevel.DEBUG | Inserting payment payment_hash: PaymentHash([118, 63, 192, 200, 120, 59, 14, 206, 226, 15, 93, 231, 133, 81, 15, 144, 109, 159, 25, 11, 22, 63, 102, 170, 85, 30, 172, 87, 38, 173, 247, 138]) 
| 2023-07-26 18:06:55.441 | LogLevel.TRACE | lightning_background_processor: Persisting ChannelManager...  
| 2023-07-26 18:06:55.441 | LogLevel.ERROR | Failed to pay funding transaction fees of 153000 msats to 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802. Error: Failed to send payment: Route not found, lnbcrt1530n1pjvp4qldqqnp4qdg8hyjd4ejetnahsjfy3xtczf79783cw7zg2ex7yq2u6m2pxavqypp5wclupjrc8v8vacs0thnc25g0jpke7xgtzclkd2j4r6k9wf4d779qsp5chqzmgrg7k2y5wq68g4euws4q98lszxawlr8536yr7v4c6qqmdzq9qyysgqcqpcxqz95drunqze3trmmk9xcy6pkcaf32dsd9xtqx3wdjh9x7wwhkptfdrgrd4e4v4m5qwwvyzy6msvfnx60p6un8yv5xz96r54hwgpt8t34s8gqhwagel  
```

---

We can also see this happening on CI (sometimes?). The test is failing to find a route right after receiving a payment on the very same channel.

Test is failing to find a route on CI
```
2023-07-03T11:56:02.576296Z TRACE lightning::routing::router: Skipped direct route to payee via SCID 1099514970117    
2023-07-03T11:56:02.576349Z TRACE lightning::routing::router: Starting main path collection loop with 1 nodes pre-filled from first/last hops.    
2023-07-03T11:56:02.576381Z TRACE lightning::routing::router: Skipped direct route to payee via SCID 1099514970117    
2023-07-03T11:56:02.576420Z TRACE lightning::routing::router: Starting main path collection loop with 1 nodes pre-filled from first/last hops.    
2023-07-03T11:56:02.576446Z TRACE lightning::routing::router: Have now collected 0 msat (seeking 459000 msat) in paths. Last path loop did not find a new path.    
2023-07-03T11:56:02.576540Z ERROR ln_dlc_node::node::invoice: Failed to send payment err=RouteNotFound
```

Test is succeeding on a local run
```
2023-07-03T17:46:41.421075Z TRACE lightning::routing::router: Searching for a route from payer 03d2ca1a6045fc646a161fb657f062a6b7846d8540cd37b37d130c7c50b1ad6379 to payee 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9 with MPP and 1 first hops overriding the network graph    
2023-07-03T17:46:41.421118Z TRACE lightning::routing::router: Building path from 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9 (payee) to 03d2ca1a6045fc646a161fb657f062a6b7846d8540cd37b37d130c7c50b1ad6379 (us/payer) for value 153000 msat.    
2023-07-03T17:46:41.421163Z TRACE lightning::routing::router: Added direct route to payee via SCID 1099627036673    
2023-07-03T17:46:41.421205Z TRACE lightning::routing::router: Starting main path collection loop with 4 nodes pre-filled from first/last hops.    
2023-07-03T17:46:41.421233Z TRACE lightning::routing::router: Found a path back to us from the target with 1 hops contributing up to 153000 msat: 
 [
    PathBuildingHop {
        node_id: NodeId(02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9),
        short_channel_id: 1099627036673,
        total_fee_msat: 0,
        next_hops_fee_msat: 0,
        hop_use_fee_msat: 0,
        total_fee_msat - (next_hops_fee_msat + hop_use_fee_msat): 0,
        path_penalty_msat: 501,
        path_htlc_minimum_msat: 0,
        cltv_expiry_delta: 0,
    },
]    
2023-07-03T17:46:41.421254Z TRACE lightning::routing::router: Disabling channel 1099627036673 for future path building iterations to avoid duplicates.    
2023-07-03T17:46:41.421260Z TRACE lightning::routing::router: Collected exactly our payment amount on the first pass, without hitting an htlc_minimum_msat limit, exiting.    
2023-07-03T17:46:41.421312Z  INFO lightning::routing::router: Got route to 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9: path 0:
 node_id: 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9, short_channel_id: 1099627036673, fee_msat: 153000, cltv_expiry_delta: 24
    
```

### PR DESCRIPTION
**Pull request by holzeis**
fixes #883

### CODE REVIEW

File: mobile/native/src/api.rs [hunk 1]
```diff
@@ -231,7 +230,6 @@ pub fn run(
     db::init_db(&app_dir, get_network())?;
     let runtime = ln_dlc::get_or_create_tokio_runtime()?;
     ln_dlc::run(app_dir, seed_dir, runtime)?;
-    event::subscribe(ChannelFeePaymentSubscriber::new());
```
Comment (luckysori) [inline mobile/native/src/api.rs:234]: ❓Why did we have to move this?

File: mobile/native/src/channel_fee.rs [hunk 2]
```diff
@@ -51,22 +55,31 @@ impl Subscriber for ChannelFeePaymentSubscriber {
...
             None => {
                 tracing::debug!("No pending funding transaction found!");
                 return Ok(());
             }
         };
 
+        tokio::task::block_in_place(|| {
+            tracing::debug!(
+                "Waiting for outbound capacity on channel {}.",
+                hex::encode(channel_id)
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs]: 🙃 Slightly prefer using `tracing` fields.
```suggestion
                channel_id = %hex::encode(channel_id),
                "Waiting for outbound capacity on channel",
```

File: mobile/native/src/channel_fee.rs [hunk 3]
```diff
@@ -128,12 +141,40 @@ impl ChannelFeePaymentSubscriber {
...
             .clone()
     }
+
+    async fn wait_for_outbound_capacity(&self, channel_id: ChannelId) -> Result<()> {
+        tokio::time::timeout(Duration::from_secs(5), async {
+            loop {
+                let channel_details = self
+                    .channel_manager
+                    .get_channel_details(&channel_id)
+                    .expect("Channel details to exist");
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs:166]: 🔧 This could panic if the channel is closed whilst we wait for this.

File: mobile/native/src/channel_fee.rs [hunk 4]
```diff
@@ -128,12 +141,40 @@ impl ChannelFeePaymentSubscriber {
...
+                tracing::debug!("------> Channel Details: {:?}", channel_details);
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs]: 🔧 Can remove this.

File: mobile/native/src/channel_fee.rs [hunk 5]
```diff
@@ -9,17 +9,21 @@ use anyhow::Context;
...
 use std::str::FromStr;
 use std::sync::Arc;
 use std::sync::Mutex;
+use std::time::Duration;
 use tokio::runtime::Handle;
 
 #[derive(Clone)]
 pub struct ChannelFeePaymentSubscriber {
-    pub open_channel_tx: Arc<Mutex<Option<EsploraTransaction>>>,
+    pub open_channel_tx: Arc<Mutex<Option<(ChannelId, EsploraTransaction)>>>,
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs:25]: 🔧 Since we store two things now?

```suggestion
    pub open_channel_info: Arc<Mutex<Option<(ChannelId, EsploraTransaction)>>>,
```

File: mobile/native/src/channel_fee.rs [hunk 6]
```diff
@@ -128,12 +146,43 @@ impl ChannelFeePaymentSubscriber {
...
+                } else {
+                    tracing::debug!(channel_id = hex::encode(channel_id), outbound_capacity_msats = channel_details.outbound_capacity_msat, funding_tx_fees_msats,
+                        "Channel does not have enough outbound capacity to pay jit channel opening fees yet. Waiting.");
+                    tokio::time::sleep(Duration::from_millis(200)).await
+                }
+            }
+        })
+        .await
+        .map_err(|e| anyhow!("{e:#}"))
+        .context(format!(
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs:181]: 🔧 Should use `with_context` instead.

```suggestion
        .with_context(|| format!(
```

File: mobile/native/src/channel_fee.rs [hunk 7]
```diff
@@ -51,24 +55,38 @@ impl Subscriber for ChannelFeePaymentSubscriber {
...
         let funding_tx_fees_msats = (transaction.fee * 1000) as u64;
+
+        tokio::task::block_in_place(|| {
+            tracing::debug!(
+                "Waiting for outbound capacity on channel {} to pay {funding_tx_fees_msats} msats jit channel opening fee.",
+                hex::encode(channel_id)
+            );
+            Handle::current()
+                .block_on(self.wait_for_outbound_capacity(channel_id, funding_tx_fees_msats))
+        })?;
```
Comment (luckysori) [inline mobile/native/src/channel_fee.rs:84]: 👍 I think this is okay. You could write a non-async `wait_for_outbound_capacity` so that you don't need to do all this, but I guess `tokio::time::timeout` is very convenient.

**Review by luckysori — APPROVED** [review]
LGTM!

Try to use `tracing` fields wherever you can though 😛

File: mobile/native/src/api.rs (hunk 1 above)
Comment (holzeis) [reply mobile/native/src/api.rs:234]: because I needed the `channel_manager` when creating the `ChannelFeePaymentSubscriber`

File: mobile/native/src/channel_fee.rs (hunk 3 above)
Comment (holzeis) [reply mobile/native/src/channel_fee.rs:166]: that would be very unlucky, but I've changed it. good find :)

File: mobile/native/src/channel_fee.rs (hunk 6 above)
Comment (holzeis) [reply mobile/native/src/channel_fee.rs:181]: well.. happy to change it, but do you think printing the text is such a huge performance cost, that we have to do it lazily? or do you have other reasons for suggesting that?

File: mobile/native/src/channel_fee.rs [hunk 8]
```diff
@@ -110,30 +123,64 @@ impl ChannelFeePaymentSubscriber {
...
+                let channel_details = match self
+                    .channel_manager
+                    .get_channel_details(&channel_id) {
+                    Some(channel_details) => channel_details,
+                    None => {
+                        bail!("Could not find channel details for {}", hex::encode(channel_id));
+                    },
+                };
+
+                if channel_details.outbound_capacity_msat >= funding_tx_fees_msats {
```
Comment (bonomat) [inline mobile/native/src/channel_fee.rs:167]: Do we need to check if the channel is `usable` aswell?

**Review by bonomat — APPROVED** [review]
If it works, I'd say let's get it in.

File: mobile/native/src/channel_fee.rs [hunk 9]
```diff
@@ -31,9 +34,7 @@ pub struct EsploraTransaction {
 impl Subscriber for ChannelFeePaymentSubscriber {
     fn notify(&self, event: &EventInternal) {
         let result = match event {
-            EventInternal::ChannelReady(channel_id) => {
-                self.register_funding_transaction(channel_id)
-            }
+            EventInternal::ChannelReady(channel_id) => self.register_channel_open_info(channel_id),
             EventInternal::PaymentClaimed(amount_msats) => {
                 self.pay_funding_transaction_fees(*amount_msats)
```
[the remark this answers is not in the document]
Comment (holzeis) [reply mobile/native/src/channel_fee.rs:39]: Granted it's not that obvious, but the result isn't ignored. It is returned and handled below.

https://github.com/get10101/10101/pull/1015/files#diff-0794547da0f3f908cacefe532d16f7809a8a3eb8931623ced112fb3ef15354b1L43-L45

File: mobile/native/src/channel_fee.rs (hunk 6 above)
Comment (luckysori) [reply mobile/native/src/channel_fee.rs]: I'm sure it's negligible, but I think it's more correct to use `with_context` when you have to build the error so that it is evaluated lazily.

So obviously not a big deal at all, but I wouldn't know why not to do it.

File: mobile/native/src/channel_fee.rs (hunk 8 above)
Comment (holzeis) [reply mobile/native/src/channel_fee.rs:167]: The channel was always `usable`..

File: mobile/native/src/channel_fee.rs (hunk 6 above)
Comment (luckysori) [reply mobile/native/src/channel_fee.rs]: @holzeis just pointing out that I didn't mean to say to _always_ use `with_context`. It depends on the... context 😛

Comment (Restioson) [reply mobile/native/src/channel_fee.rs]: `format!` itself also incurs an allocation since it makes a String
