### PR TITLE
fix: ensure filling/filled orders have matching fee

### LINKED ISSUE #2382: Failed to start 10101! (test app)
### Contact

@SXBT69 

### The Problem

App won't start

### The ScreenShots

image

### The Logs
[2024-04-08_223208.log](https://github.com/get10101/meta/files/14912744/2024-04-08_223208.log)

### PR DESCRIPTION
**Pull request by bonomat**
resolves #2382 (hopefully). 

It ensures that this bug cannot happen again and sets the matching fee for existing orders in the db. 
My interpretation is that this error came from the fact that we introduced a new field `matching_fee_sats` which was obviously not set for existing orders.

### CODE REVIEW

File: mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/up.sql [hunk 1]
```diff
@@ -0,0 +1,17 @@
+-- Your SQL goes here
+update orders
+set matching_fee_sats = quantity / (execution_price * leverage) * 100000000
```
Comment (holzeis) [inline mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/up.sql:3]: 🔧 I think this is missing the fee_rate

```suggestion
set matching_fee_sats = quantity / (execution_price * leverage) * 100000000 * 0.003
```

**Review by holzeis — APPROVED** [review]
LGTM 👍 

fyi: I've deployed this branch on my regtest app and can confirm that this is fixing the issue ;)

File: mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/up.sql (hunk 1 above)
Comment (bonomat) [reply mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/up.sql:3]: Makes sense 🙈
