### PR TITLE
Add `await` to fix app initialisation

### LINKED ISSUE #1002: Candlestick chart loads indefinitely
As seen in the screenshot below, the candlestick chart on the trade screen loads indefinitely.

image

### PR DESCRIPTION
**Pull request by Restioson**
If this is not awaited, then something tries to access the database before it is ready.

@klochowicz I think you just left this out by mistake?  Trivial fix in the end!

Fixes #1002.

### CODE REVIEW

File: mobile/lib/main.dart [hunk 1]
```diff
@@ -257,7 +257,7 @@ class _TenTenOneAppState extends State<TenTenOneApp> {
 
       subscribeToNotifiers(context);
 
-      runBackend(config).then((_) {
+      await runBackend(config).then((_) {
```
Comment (holzeis) [inline mobile/lib/main.dart:260]: 🙃 if we `await` here we can move the `Flog.info` simply below the `runBackend(config);` line.

Comment (bonomat) [reply mobile/lib/main.dart]: I did it for you @Restioson

**Review by bonomat — APPROVED** [review]
Thank you for the fix. Let's get this in as it fixes the app.
