### PR TITLE
Fix pull-down refresh

### LINKED ISSUE #313: Fix pull-down refresh for the wallet
We have the possibility to trigger a refresh in Dart, so we can actually add this feature easily.

### PR DESCRIPTION
**Pull request by Restioson**
Fixes #313

### CODE REVIEW

File: mobile/lib/features/wallet/wallet_screen.dart [hunk 1]
```diff
@@ -224,20 +225,29 @@ class _WalletScreenState extends State<WalletScreen> {
...
-                  itemBuilder: (BuildContext context, int index) {
-                    // Spacer at the bottom of the list
-                    if (index == walletChangeNotifier.walletInfo.history.length) {
-                      return listBottomScrollSpace;
-                    }
+                child: ScrollConfiguration(
+                  behavior: ScrollConfiguration.of(context).copyWith(
+                    dragDevices: {
+                      PointerDeviceKind.touch,
+                      PointerDeviceKind.mouse,
```
Comment (Restioson) [inline mobile/lib/features/wallet/wallet_screen.dart:232]: This makes it possible on desktop, which is a nice QoL feature for development

**Review by klochowicz — APPROVED** [review]
