### PR TITLE
fix: Do not call periodic check twice

### LINKED ISSUE #1586: Node panics when trying to finalize closing established channel
The coordinator is panicking when trying to get the attestation from the oracle.

```
2023-11-16 13:00:51  INFO dlc_manager::manager: Buffer transaction for contract 66e5200035982870036d061b59157d7f856f74077496cdd7829dff0e47ea6390 has enough confirmations to spend from it    
2023-11-16 13:00:51 DEBUG reqwest::connect: starting new connection: http://localhost:8081/    
2023-11-16 13:00:51  INFO ln_dlc_node::ldk_node_wallet: Broadcasting transaction txid=e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5 raw_tx=020000000001017601004a203c1856e61bda3bdbd8d411b632c0d34f6efacc93ef59fec86c791e000000000020010000026a31000000000000160014fc9dbf9f258091ca8f3677bd05615a1339702a6a7c37000000000000160014d9c449146b6e77fb25e1a0cb9df8a4f1bfb76b9f0347304402200ab63a163bbd8b686ed14255780457e263a41113428008af50b61db364aed150022057400cde7630c0442c751156e1cee55629105512edc8c1e011cd18a6202d6ec201483045022100a28aa34005aa993147a38a03244696506958d7a4fec5e1f2c36b6756007733df0220267d2991388fec96f00ed97db2fbc33371f493af2a0896ece4f9248757cdc94501e021025931a2e3f4f7d56d0257dc5fdd82d2d37c8b593a0ddd1daba79a7002a01ea7cdac646376a91455780dc712c2f1826a1e7d19324bb499c535d56488ad76a914154e89e8f2f82a3dc996e78122f756c0db1e2e3288ad76a9148fef66593ad2cb3d652e6ee8b2b56f928c0dcfe0886776a914ee6e7d71ca580fc8e54995842e4d9e4ca2dfd24d88ad76a914e3e29723c6fd4a7e1647d5995875fcafc484558b88ad76a914e09640febf6b4b1fceb561b51e757cda1fbb39ea8868672103c3b7f1367298c06c68d46d02bb7e449b26688c7ef57a6720b7218f753069cf8a68acb9105665
2023-11-16 13:00:52 ERROR dlc_manager::manager: Error trying to close established channel: Wallet error Failed to broadcast transaction e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5    
2023-11-16 13:00:53  INFO dlc_manager::chain_monitor: Transaction e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5 confirmed: ChannelInfo { channel_id: [230, 19, 247, 96, 242, 241, 55, 93, 104, 96, 227, 207, 95, 159, 125, 122, 149, 183, 249, 52, 117, 87, 80, 79, 4, 225, 202, 179, 96, 168, 55, 61], tx_type: Cet }    
2023-11-16 13:00:53  INFO dlc_manager::manager: Buffer transaction for contract 66e5200035982870036d061b59157d7f856f74077496cdd7829dff0e47ea6390 has enough confirmations to spend from it    
2023-11-16 13:00:53 ERROR coordinator: Aborting after panic in task info=panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/shutdown.rs:51:21
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/backtrace.rs:332:13
   3: coordinator::main::{{closure}}::{{closure}}
             at ./coordinator/src/bin/coordinator.rs:61:29
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   8: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   9: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  10: tokio::runtime::blocking::shutdown::Receiver::wait
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/shutdown.rs:51:21
  11: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:261:12
  12: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:278:9
  13: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mod.rs:490:1
  14: core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mod.rs:490:1
  15: reqwest::blocking::wait::enter
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/wait.rs:76:21
  16: reqwest::blocking::wait::timeout
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/wait.rs:13:5
  17: reqwest::blocking::client::ClientHandle::new
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/client.rs:1042:15
  18: reqwest::blocking::client::ClientBuilder::build
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/client.rs:103:9
  19: reqwest::blocking::get
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/mod.rs:107:5
  20: p2pd_oracle_client::get
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/p2pd-oracle-client/src/lib.rs:78:5
  21: <p2pd_oracle_client::P2PDOracleClient as dlc_manager::Oracle>::get_attestation
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/p2pd-oracle-client/src/lib.rs:164:13
  22: dlc_manager::manager::Manager<W,B,S,O,T,F>::get_closable_contract_info::{{closure}}
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:597:29
  23: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:298:13
  24: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/iter/macros.rs:266:38
  25: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/adapters/filter_map.rs:61:9
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/spec_from_iter.rs:33:9
  28: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/mod.rs:2712:9
  29: core::iter::traits::iterator::Iterator::collect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:1896:9
  30: dlc_manager::manager::Manager<W,B,S,O,T,F>::get_closable_contract_info
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:591:44
  31: dlc_manager::manager::Manager<W,B,S,O,T,F>::try_finalize_closing_established_channel
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:1178:63
  32: dlc_manager::manager::Manager<W,B,S,O,T,F>::channel_checks
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:1949:29
  33: dlc_manager::manager::Manager<W,B,S,O,T,F>::periodic_check
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:400:9
  34: ln_dlc_node::node::manage_dlc_manager::{{closure}}
             at ./crates/ln-dlc-node/src/node/mod.rs:889:33
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:296:9
  36: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  39: ___rust_try
  40: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  41: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  42: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  43: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/remote_handle.rs:105:29
  44: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  45: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  46: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  47: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  48: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  49: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  50: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  51: ___rust_try
  52: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  53: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  54: tokio::runtime::task::harness::poll_future
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  55: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  56: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  57: tokio::runtime::task::raw::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  58: tokio::runtime::task::raw::RawTask::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  59: tokio::runtime::task::LocalNotified<S>::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  60: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  61: tokio::runtime::coop::with_budget
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  62: tokio::runtime::coop::budget
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  63: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  64: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  65: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  66: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  67: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  68: tokio::runtime::scheduler::multi_thread::worker::block_in_place::{{closure}}::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:343:41
  69: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  70: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  77: ___rust_try
  78: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  79: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  80: tokio::runtime::task::harness::poll_future
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  83: tokio::runtime::task::raw::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  86: tokio::runtime::blocking::pool::Task::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  89: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  90: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:526:17
  91: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  92: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  93: ___rust_try
  94: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  95: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  96: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:525:30
  97: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  98: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  99: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
 100: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
 101: __pthread_joiner_wake

[1]    16677 abort      cargo run --bin coordinator -- 
```

_Originally posted by @holzeis in https://github.com/get10101/10101/issues/1466#issuecomment-1814396485_

### PR DESCRIPTION
**Pull request by holzeis**
The periodic check is already called in a loop by the `sub_channel_manager_periodic_check`. I don't see a reason to do it multiple times.

Also finalizing a force-closure with the `period_check` called from the manager lead to a panic, when trying to get the attestations from the oracle.

fixes #1586

### CODE REVIEW

**Comment by holzeis** [comment]
Note, this may also explain why the force-closure ln-dlc tests are sometimes failing, as it seems to be pure chance which periodic check gets called to finalized the dlc channel force closure.

**Review by luckysori — APPROVED** [review]
LGTM. Two things:

- I have no idea why I added it with the upgrade to 0.0.116 🤷
- I have no idea why calling a `periodic_check` should panic!! We should look into that.

File: crates/ln-dlc-node/src/node/mod.rs [hunk 1]
```diff
@@ -883,12 +883,10 @@ fn manage_dlc_manager<S: TenTenOneStorage + 'static, N: Storage + Sync + Send +
             loop {
                 tracing::trace!("Started periodic dlc manager check");
```
Comment (luckysori) [inline crates/ln-dlc-node/src/node/mod.rs:884]: Since you've changed this it would be nice to align the whole function including the logs to reflect that this task is now solely about calling `periodic_chain_monitor` i.e. feeding new blocks to the `rust-dlc` `ChainMonitor`.
