### PR TITLE
fix: Spawn blocking on force-close and close channel

### LINKED ISSUE #1598: Panic when finishing force-closure of channel
```
2023-11-17T11:34:48.823294Z DEBUG log: Finishing force-closure of channel with 0 HTLCs to fail log.target="lightning::ln::channelmanager" log.module_path="lightning::ln::channelmanager" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/ln/channelmanager.rs" log.line=2735
2023-11-17T11:34:48.823341Z TRACE log: Updating ChannelMonitor for channel 304c6ab05be34318bb9b7f0cc20d29ebce2f5d2177fc6729c6c0aeccbab7e6da log.target="lightning::chain::chainmonitor" log.module_path="lightning::chain::chainmonitor" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/chain/chainmonitor.rs" log.line=741
2023-11-17T11:34:48.823383Z  INFO log: Applying force close update to monitor 304c6ab05be34318bb9b7f0cc20d29ebce2f5d2177fc6729c6c0aeccbab7e6da with 1 change(s). log.target="lightning::chain::channelmonitor" log.module_path="lightning::chain::channelmonitor" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/chain/channelmonitor.rs" log.line=2473
2023-11-17T11:34:48.823418Z TRACE log: Updating ChannelMonitor: channel force closed, should broadcast: true log.target="lightning::chain::channelmonitor" log.module_path="lightning::chain::channelmonitor" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/chain/channelmonitor.rs" log.line=2533
2023-11-17T11:34:48.82345Z DEBUG log: Getting signed latest holder commitment transaction! log.target="lightning::chain::channelmonitor" log.module_path="lightning::chain::channelmonitor" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/chain/channelmonitor.rs" log.line=3066
2023-11-17T11:34:48.825032Z  INFO log: Broadcasting local commitment tx with txid 4d75efcea7d614bf8cc3a4a83cd7ae7fd6c69f060ff829e091dd65fd075e8ca1 log.target="lightning::chain::channelmonitor" log.module_path="lightning::chain::channelmonitor" log.file="/Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/a57281b/lightning/src/chain/channelmonitor.rs" log.line=2457
2023-11-17T11:34:48.825327Z  INFO ln_dlc_node::ldk_node_wallet: Broadcasting transaction txid=4d75efcea7d614bf8cc3a4a83cd7ae7fd6c69f060ff829e091dd65fd075e8ca1 raw_tx=02000000000101304c6ab05be34318bb9b7f0cc20d29ebce2f5d2177fc6729c6c0aeccbab7e6da0000000000de03c98002905f0100000000002200209a0fc2a8f5a8538d14c34dfbfbb001a98067a7117bc89d9c5a578fe98daebdabf9ac0100000000001600146e94ddbc96a8cd383762bc07d62b710e2237cba5040047304402206d407fe637109868915076579229a037e76c987e70445abb57e24aa405c5788f022069d7fad7da9386adb043c98c9a4a005725425a4e922495cb52e3e93ce53682540147304402201f223022447b338da733deb26c1852dbfa01da3e3b17bf0281dc8bf810d0e0990220115d5adaa9c6f2307d9f9f5a3b6a8b1374bc8903d697616d33d7185b15ead3990147522102844c0b05abfac2c793bd38e016ed758bd88a4290a56162c730faa474ae9d7df12103b0255101fd43d026f4088c6266085bd402d1d0121e02a6e7b37f15dc14899a4652ae71ac3f20
2023-11-17T11:34:48.825654Z DEBUG native::db: Upserting transaction transaction=Transaction { txid: 4d75efcea7d614bf8cc3a4a83cd7ae7fd6c69f060ff829e091dd65fd075e8ca1, fee: 0, created_at: 2023-11-17 11:34:48.82539 +00:00:00, updated_at: 2023-11-17 11:34:48.82539 +00:00:00, raw: "02000000000101304c6ab05be34318bb9b7f0cc20d29ebce2f5d2177fc6729c6c0aeccbab7e6da0000000000de03c98002905f0100000000002200209a0fc2a8f5a8538d14c34dfbfbb001a98067a7117bc89d9c5a578fe98daebdabf9ac0100000000001600146e94ddbc96a8cd383762bc07d62b710e2237cba5040047304402206d407fe637109868915076579229a037e76c987e70445abb57e24aa405c5788f022069d7fad7da9386adb043c98c9a4a005725425a4e922495cb52e3e93ce53682540147304402201f223022447b338da733deb26c1852dbfa01da3e3b17bf0281dc8bf810d0e0990220115d5adaa9c6f2307d9f9f5a3b6a8b1374bc8903d697616d33d7185b15ead3990147522102844c0b05abfac2c793bd38e016ed758bd88a4290a56162c730faa474ae9d7df12103b0255101fd43d026f4088c6266085bd402d1d0121e02a6e7b37f15dc14899a4652ae71ac3f20" }
2023-11-17T11:34:48.865791Z ERROR native::api: Aborting after panic in task info=panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', mobile/native/src/backup.rs:192:9
   0: std::backtrace::Backtrace::create
   1: native::api::run::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_display
   8: tokio::runtime::scheduler::Handle::current
   9: tokio::runtime::handle::Handle::current
  10: tokio::task::spawn::spawn_inner
  11: tokio::task::spawn::spawn
  12: native::backup::RemoteBackupClient::backup
  13: <native::storage::TenTenOneNodeStorage as lightning::util::persist::KVStorePersister>::persist
  14: lightning::util::persist::<impl lightning::chain::chainmonitor::Persist<ChannelSigner> for K>::update_persisted_channel
  15: <lightning::chain::chainmonitor::ChainMonitor<ChannelSigner,C,T,F,L,P> as lightning::chain::Watch<ChannelSigner>>::update_channel
  16: lightning::ln::channelmanager::ChannelManager<M,T,ES,NS,SP,F,R,L>::finish_force_close_channel
  17: lightning::ln::channelmanager::ChannelManager<M,T,ES,NS,SP,F,R,L>::force_close_channel_with_peer
  18: lightning::ln::channelmanager::ChannelManager<M,T,ES,NS,SP,F,R,L>::force_close_sending_error
  19: lightning::ln::channelmanager::ChannelManager<M,T,ES,NS,SP,F,R,L>::force_close_broadcasting_latest_txn
  20: ln_dlc_node::node::ln_channel::<impl ln_dlc_node::node::Node<S,N>>::force_close_channel
  21: ln_dlc_node::node::ln_channel::<impl ln_dlc_node::node::Node<S,N>>::close_channel
  22: native::ln_dlc::close_channel
  23: native::api::force_close_channel
  24: native::bridge_generated::bridge_generated::wire_force_close_channel_impl::{{closure}}::{{closure}}
  25: <flutter_rust_bridge::handler::ThreadPoolExecutor<EH> as flutter_rust_bridge::handler::Executor>::execute::{{closure}}::{{closure}}
  26: std::panicking::try::do_call
  27: ___rust_try
  28: std::panicking::try
  29: std::panic::catch_unwind
  30: <flutter_rust_bridge::handler::ThreadPoolExecutor<EH> as flutter_rust_bridge::handler::Executor>::execute::{{closure}}
  31: <F as threadpool::FnBox>::call_box
  32: threadpool::spawn_in_pool::{{closure}}
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: std::panicking::try::do_call
  37: ___rust_try
  38: std::panicking::try
  39: std::panic::catch_unwind
  40: std::thread::Builder::spawn_unchecked_::{{closure}}
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: std::sys::unix::thread::Thread::new::thread_start
  43: __pthread_joiner_wake
```

### PR DESCRIPTION
**Pull request by holzeis**
fixes #1598

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
This is fine, but I would prefer to use the static runtime when spawning instead.

File: mobile/native/src/api.rs [hunk 1]
```diff
@@ -286,11 +286,13 @@ pub fn get_unused_address() -> SyncReturn<String> {
 }
 
 pub fn close_channel() -> Result<()> {
-    ln_dlc::close_channel(false)
+    let runtime = ln_dlc::get_or_create_tokio_runtime()?;
+    runtime.block_on(async { ln_dlc::close_channel(false).await })
```
Comment (luckysori) [inline mobile/native/src/api.rs:290]: This is not what I meant. I said that we should use the static runtime to spawn wherever we were running into this kind of panic: 

```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

The whole idea was not to make `close_channel` and others `async`. Making things `async` unnecessarily is a risk because then we have to be careful not to add blocking code there.

Comment (holzeis) [reply mobile/native/src/api.rs:290]: Have a look at https://github.com/get10101/10101/pull/1610
