### PR TITLE
Ensure separate sqlite DB is used for different networks

### LINKED ISSUE #277: App database file location is shared between all networks
In particular, if a dev first runs the app on testnet and then on regtest, the same database file (`trader.sqlite`) will be used for both. This could result in unexpected behaviour or simply overwriting data by mistake.

### PR DESCRIPTION
**Pull request by klochowicz**
Closes #277

### CODE REVIEW

File: mobile/native/src/db/mod.rs [hunk 1]
```diff
@@ -61,8 +62,8 @@ impl r2d2::CustomizeConnection<SqliteConnection, r2d2::Error> for ConnectionOpti
     }
 }
 
-pub fn init_db(db_dir: String) -> Result<()> {
-    let database_url = format!("sqlite://{db_dir}/trader.sqlite");
+pub fn init_db(db_dir: &str, network: bitcoin::Network) -> Result<()> {
+    let database_url = format!("sqlite://{db_dir}/{network}.sqlite");
```
Comment (da-kami) [inline mobile/native/src/db/mod.rs:66]:
```suggestion
    let database_url = format!("sqlite://{db_dir}/{network}-trades.sqlite");
```

I would still indicate that this is the database that stores the trades / 10101 data and not just "Bitcoin related".
It might be confusing to people that we use the network as database name.

We could also consider moving the data into the network folder, but I'm not sure that's less confusing. 
Not super important though.

**Review by da-kami — APPROVED** [review]

File: mobile/native/src/db/mod.rs (hunk 1 above)
Comment (klochowicz) [reply mobile/native/src/db/mod.rs:66]: how about `trader-$NETWORK`?

**Review by luckysori — APPROVED** [review]

File: mobile/native/src/db/mod.rs (hunk 1 above)
Comment (klochowicz) [reply mobile/native/src/db/mod.rs:66]: I'll go with `trades-{network}.sqlite` - good suggestion! :)
