### PR TITLE
Fix: failed to close position got revoke commitment secret not matching their current pubkey

### LINKED ISSUE #792: Failed to close position: Failed to handle SubChannelCloseFinalize
Although my position was shown as closed successfully, opening another position failed as there exist a non-closed position. Checking the logs at the coordinator I found the following error after processing the SubChannelCloseFinalize message from the app.

```
Failed to process message: Failed to handle SubChannelCloseFinalize message from 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8: Invalid state: Misuse error: Close : Got a revoke commitment secret which didn't correspond to their current pubkey
```

It appears my phone lost the connection while the position was closed. That's most likely the reason for the error. The app is now stuck, as I can't open another position or recover the closed on.

```
2023-06-17T17:57:55Z	{"timestamp":"2023-06-17T17:57:55.115809296Z","level":"ERROR","fields":{"message":"Failed to process message: Failed to handle SubChannelCloseFinalize message from 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8: Invalid state: Misuse error: Close : Got a revoke commitment secret which didn't correspond to their current pubkey","from":"02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","kind":"SubChannelCloseFinalize"},"target":"coordinator::node"}
2023-06-17T17:57:55Z	{"timestamp":"2023-06-17T17:57:55.111790453Z","level":"INFO","fields":{"message":"Processing message","from":"02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","kind":"SubChannelCloseFinalize"},"target":"coordinator::node"}
2023-06-17T17:57:55Z	{"timestamp":"2023-06-17T17:57:55.107657568Z","level":"INFO","fields":{"message":"Background sync of Lightning wallet finished in 1ms."},"target":"ln_dlc_node::node"}
2023-06-17T17:57:55Z	{"timestamp":"2023-06-17T17:57:55.107638173Z","level":"INFO","fields":{"message":"Finished transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":178},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:57:55Z	{"timestamp":"2023-06-17T17:57:55.105770355Z","level":"INFO","fields":{"message":"Starting transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":92},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142811857Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142603877Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142572554Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142460713Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142359664Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:51Z	{"timestamp":"2023-06-17T17:57:51.142118175Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.728107851Z","level":"DEBUG","fields":{"message":"Error handling message from 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8; ignoring: Couldn't find channel for update","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/peer_handler.rs","log.line":1292},"target":"lightning::ln::peer_handler"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.728061511Z","level":"DEBUG","fields":{"message":"Received channel_update for channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0.","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channelmanager.rs","log.line":5255},"target":"lightning::ln::channelmanager"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.727828915Z","level":"DEBUG","fields":{"message":"Restored monitor updating in channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0 resulting in no commitment update and no RAA, with commitment first","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":3863},"target":"lightning::ln::channel"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.725428626Z","level":"INFO","fields":{"message":"Applying update to monitor b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0, bringing update_id from 10 to 11 with 1 changes.","log.target":"lightning::chain::channelmonitor","log.module_path":"lightning::chain::channelmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/chain/channelmonitor.rs","log.line":2298},"target":"lightning::chain::channelmonitor"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.725394266Z","level":"DEBUG","fields":{"message":"Received a valid revoke_and_ack for channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0 with no reply necessary.","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":3610},"target":"lightning::ln::channel"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.584371081Z","level":"DEBUG","fields":{"message":"Reconnected channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0 with no loss","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":4120},"target":"lightning::ln::channel"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.451331526Z","level":"DEBUG","fields":{"message":"Handling SendChannelReestablish event in peer_handler for node 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8 for channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/peer_handler.rs","log.line":1800},"target":"lightning::ln::peer_handler"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.451265887Z","level":"DEBUG","fields":{"message":"Handling SendChannelAnnouncement event in peer_handler for node 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8 for short channel id 873225537837203457","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/peer_handler.rs","log.line":1806},"target":"lightning::ln::peer_handler"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.450674519Z","level":"DEBUG","fields":{"message":"Generating channel_reestablish events for 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channelmanager.rs","log.line":6548},"target":"lightning::ln::channelmanager"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.45062963Z","level":"INFO","fields":{"message":"Received peer Init message from 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8: DataLossProtect: supported, InitialRoutingSync: not supported, UpfrontShutdownScript: supported, GossipQueries: supported, VariableLengthOnion: required, StaticRemoteKey: required, PaymentSecret: required, BasicMPP: supported, Wumbo: supported, AnchorsZeroFeeHtlcTx: not supported, ShutdownAnySegwit: supported, OnionMessages: not supported, ChannelType: supported, SCIDPrivacy: supported, ZeroConf: supported, unknown flags: none","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/peer_handler.rs","log.line":1333},"target":"lightning::ln::peer_handler"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.317233726Z","level":"DEBUG","fields":{"message":"Finished noise handshake for connection with 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/peer_handler.rs","log.line":1205},"target":"lightning::ln::peer_handler"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.118769194Z","level":"DEBUG","fields":{"message":"Marking channels with 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8 disconnected and generating channel_updates.","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channelmanager.rs","log.line":6445},"target":"lightning::ln::channelmanager"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.113319991Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.113083383Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.113050149Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.112920035Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.112813974Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.112552434Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.107707955Z","level":"DEBUG","fields":{"message":"Received inbound connection","addr":"80.121.45.204:50190"},"target":"ln_dlc_node::node"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.10766565Z","level":"DEBUG","fields":{"message":"Received inbound connection","addr":"80.121.45.204:50186"},"target":"ln_dlc_node::node"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.104412402Z","level":"INFO","fields":{"message":"Background sync of Lightning wallet finished in 46758ms."},"target":"ln_dlc_node::node"}
2023-06-17T17:57:50Z	{"timestamp":"2023-06-17T17:57:50.10437792Z","level":"INFO","fields":{"message":"Finished transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":178},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:57:03Z	{"timestamp":"2023-06-17T17:57:03.345601085Z","level":"INFO","fields":{"message":"Starting transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":92},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.7932955Z","level":"INFO","fields":{"message":"Sending message","to":"02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","kind":"SubChannelCloseConfirm"},"target":"coordinator::node"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.7905769Z","level":"DEBUG","fields":{"message":"Restored monitor updating in channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0 resulting in no commitment update and an RAA, with commitment first","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":3863},"target":"lightning::ln::channel"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.788171641Z","level":"INFO","fields":{"message":"Applying update to monitor b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0, bringing update_id from 9 to 10 with 1 changes.","log.target":"lightning::chain::channelmonitor","log.module_path":"lightning::chain::channelmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/chain/channelmonitor.rs","log.line":2298},"target":"lightning::chain::channelmonitor"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.788154761Z","level":"DEBUG","fields":{"message":"Received valid commitment_signed from peer in channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0, updating HTLC state and responding with a revoke_and_ack.","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":3251},"target":"lightning::ln::channel"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.787808696Z","level":"DEBUG","fields":{"message":"Restored monitor updating in channel b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0 resulting in a commitment update and no RAA, with RAA first","log.target":"lightning::ln::channel","log.module_path":"lightning::ln::channel","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/ln/channel.rs","log.line":3863},"target":"lightning::ln::channel"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.783094575Z","level":"INFO","fields":{"message":"Applying update to monitor b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0, bringing update_id from 8 to 9 with 1 changes.","log.target":"lightning::chain::channelmonitor","log.module_path":"lightning::chain::channelmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning/src/chain/channelmonitor.rs","log.line":2298},"target":"lightning::chain::channelmonitor"}
2023-06-17T17:57:01Z	{"timestamp":"2023-06-17T17:57:01.776082541Z","level":"INFO","fields":{"message":"Processing message","from":"02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","kind":"SubChannelCloseAccept"},"target":"coordinator::node"}
2023-06-17T17:56:58Z	{"timestamp":"2023-06-17T17:56:58.345097704Z","level":"INFO","fields":{"message":"Background sync of Lightning wallet finished in 693ms."},"target":"ln_dlc_node::node"}
2023-06-17T17:56:58Z	{"timestamp":"2023-06-17T17:56:58.345065865Z","level":"INFO","fields":{"message":"Finished transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":178},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:56:57Z	{"timestamp":"2023-06-17T17:56:57.652013008Z","level":"INFO","fields":{"message":"Starting transaction sync.","log.target":"lightning_transaction_sync::esplora","log.module_path":"lightning_transaction_sync::esplora","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/c65cb1c/lightning-transaction-sync/src/esplora.rs","log.line":92},"target":"lightning_transaction_sync::esplora"}
2023-06-17T17:56:56Z	{"timestamp":"2023-06-17T17:56:56.528107827Z","level":"INFO","fields":{"message":"Settling DLC channel collaboratively","channel_id":"b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0","accept_settlement_amount":"10367"},"target":"ln_dlc_node::node::dlc_channel","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
2023-06-17T17:56:56Z	{"timestamp":"2023-06-17T17:56:56.528063042Z","level":"DEBUG","fields":{"message":"Closing position of 10367 with 02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8","position":"Position { id: 44, contract_symbol: BtcUsd, leverage: 2.0, quantity: 4.999704, direction: Long, average_entry_price: 25597.5, liquidation_price: 17065.0, position_state: Open, collateral: 19532, creation_timestamp: 2023-06-16 15:24:16.53064 +00:00:00, expiry_timestamp: 2023-06-18 0:00:00.0 +00:00:00, update_timestamp: 2023-06-16 15:24:16.53064 +00:00:00, trader: PublicKey(b8cb1741c52b71937db69bfbe01cc5fc0b56a34456367461b3691d341ec86faaeae307d7d40d5cfa9e62f710787e54973c2b5b0e54f1f36a9b7e64330a223d4e) }","channel_id":"b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0","accept_settlement_amount":"10367"},"target":"coordinator::node","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
2023-06-17T17:56:56Z	{"timestamp":"2023-06-17T17:56:56.524965295Z","level":"INFO","fields":{"message":"Closing position","trade_params":"TradeParams { pubkey: PublicKey(b8cb1741c52b71937db69bfbe01cc5fc0b56a34456367461b3691d341ec86faaeae307d7d40d5cfa9e62f710787e54973c2b5b0e54f1f36a9b7e64330a223d4e), contract_symbol: BtcUsd, leverage: 2.0, quantity: 4.999704, direction: Short, filled_with: FilledWith { order_id: 0a4f1595-b9d8-4031-a9d6-21697006982a, expiry_timestamp: 2023-06-19 0:00:00.0 +00:00:00, oracle_pk: XOnlyPublicKey(c071e1fd881a55831cc38c85986c6c72193b4e3a98bcbc460f6c1ed2f78cf8167458a18010faf718756c69de33ee9e38a0d3f0ad48befa58e23a4b1f843e08be), matches: [Match { order_id: a87bc5d7-0325-487f-9fe3-b087cf7fd1b4, quantity: 5, pubkey: PublicKey(7f9225001c6e5deda3aa985ff91b73d51bc5e222c6863cbe392dd37184315ff717604e65ac604059feb52794ce49f25f078cae6e785ecb1129b63ff08d969ffd), execution_price: 26409.5 }] } }","channel_id":"b64b95c06c41e56be85a25de3d6fb416c2c5bcfdbcd47364019ca076968610a0","peer_id":"02aa6fc81e341d69b36174365644a3560bfcc51ce0fb9bb67d93712bc54117cbb8"},"target":"coordinator::node","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
2023-06-17T17:56:56Z	{"timestamp":"2023-06-17T17:56:56.52491293Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
2023-06-17T17:56:56Z	{"timestamp":"2023-06-17T17:56:56.524704022Z","level":"ERROR","fields":{"message":"Failed to deserialize subchannel: Storage error Nonsense bytes didn't map to the type they were interpreted as","log.target":"dlc_sled_storage_provider","log.module_path":"dlc_sled_storage_provider","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-sled-storage-provider/src/lib.rs","log.line":474},"target":"dlc_sled_storage_provider","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
```

### PR DESCRIPTION
**Pull request by holzeis**
Fixes a bug very similar to #792. But happening during processing an outdated `Confirm` and `CloseConfirm` message. However, the bug reported with #792 fails on processing `CloseFinalize` message.

By using the dlc message handler as onion message handler we can hook into the `peer_disconnected event` and clear and pending unprocessed received `Confirm` and `CloseConfirm` messages from the disconnected peer.

See also fix in `rust-dlc` https://github.com/p2pderivatives/rust-dlc/commit/51c3c3fc4c9f468a0aa31f51a73f87149697be50

### CODE REVIEW

**Comment by holzeis** [comment]
Actually I am not entirly sure that this fix will fix #792 as the test reproduces the error on the `SubChannelConfirm` and `SubChannelCloseConfirm` messages rather than on the `SubChannelCloseFinalize` message.

However, this is certainly a fix!

File: crates/ln-dlc-node/src/node/mod.rs [hunk 1]
```diff
@@ -448,14 +447,17 @@ where
...
 
+        let dlc_message_handler = Arc::new(DlcMessageHandler::new());
+
         let lightning_msg_handler = MessageHandler {
             chan_handler: sub_channel_manager.clone(),
             route_handler: gossip_sync.clone(),
-            onion_message_handler: Arc::new(IgnoringMessageHandler {}),
+            // Hooking the dlc_message_handler here to intercept the `peer_disconnected` event and
+            // clear all pending unprocessed message from the disconnected peer. This fixes the bug
+            // https://github.com/get10101/10101/issues/792
```
Comment (luckysori) [inline crates/ln-dlc-node/src/node/mod.rs:457]: 🙃 Can we reference the bug in the commit message instead?

File: crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
Comment (luckysori) [inline crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs:1]: I would love it if we could have separate tests for all these scenarios, but I think I'm alone on this haha.

**Review by luckysori — APPROVED** [review]
Nice job! It's not the fix we were looking for, but it's important to note that the fixed bugs seem just as likely to happen.
