### PR TITLE
chore: fix reserved utxos

### LINKED ISSUE #1794: Remember locked UTXOs
When opening a dlc-channel we are locking UTXOs temporarly, however, the logic is a bit flawed and redundant, i.e. it is stored in two different DBs and one overwrites the other one.

### PR DESCRIPTION
**Pull request by bonomat**
Resolves #1794 

This PR also changes the custom fee rate logic from a fixed sats amount to a custom sats/vbyte which I think makes more sense to have.

### CODE REVIEW

File: crates/ln-dlc-node/src/ln_dlc_wallet.rs [hunk 1]
```diff
@@ -277,53 +277,57 @@ impl<S: TenTenOneStorage, N: Storage> dlc_manager::Wallet for LnDlcWallet<S, N>
         _: Option<u64>,
         lock_utxos: bool,
     ) -> Result<Vec<Utxo>, Error> {
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ln_dlc_wallet.rs:279]: 🤔 It looks to me we might run into a risk of race conditions here, in case two threads work in this function in parallel.

The reading and writing of the `reserved_outpoints` should happen mutually exclusive from any other thread.

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 2]
```diff
@@ -301,9 +286,19 @@ where
         amount_sat_or_drain: u64,
         fee: Fee,
     ) -> Result<Txid> {
+        let mut lcoked_utxos = self.locked_outpoints.lock();
         let tx = self
-            .build_psbt(address, amount_sat_or_drain, fee)?
+            .build_psbt(address, amount_sat_or_drain, fee, lcoked_utxos.clone())?
             .extract_tx();
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs]:
```suggestion
        let mut locked_utxos = self.locked_outpoints.lock();
        let tx = self
            .build_psbt(address, amount_sat_or_drain, fee)?
            .build_psbt(address, amount_sat_or_drain, fee, locked_utxos.clone())?
            .extract_tx();
```

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 3]
```diff
@@ -301,9 +286,19 @@ where
...
+
+        let prev_outpoints = tx
+            .input
+            .iter()
+            .map(|input| input.previous_output)
+            .collect::<Vec<_>>();
+
+        lcoked_utxos.extend(prev_outpoints);
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs:296]:
```suggestion
locked_utxos.extend(prev_outpoints);
```

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 4]
```diff
@@ -195,7 +190,7 @@ where
     /// Build the PSBT for sending funds to a given address and signs it
     fn build_psbt(
         &self,
-        address: &bitcoin::Address,
+        recepient: Script,
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs:193]:
```suggestion
        recipient: Script,
```

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 5]
```diff
@@ -209,13 +204,10 @@ where
 
         if amount_sat_or_drain > 0 {
             tx_builder
-                .add_recipient(address.script_pubkey(), amount_sat_or_drain)
+                .add_recipient(recepient, amount_sat_or_drain)
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs:207]:
```suggestion
                .add_recipient(recipient, amount_sat_or_drain)
```

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 6]
```diff
@@ -195,7 +190,7 @@ where
     /// Build the PSBT for sending funds to a given address and signs it
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs:190]:
```suggestion
    /// Build the PSBT for sending funds to a given output script and signs it
```

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 7]
```diff
@@ -288,7 +280,12 @@ where
...
         let mut lcoked_utxos = self.locked_outpoints.lock();
         let tx = self
-            .build_psbt(address, amount_sat_or_drain, fee, lcoked_utxos.clone())?
+            .build_psbt(
+                address.script_pubkey(),
+                amount_sat_or_drain,
+                fee,
+                lcoked_utxos.clone(),
+            )?
             .extract_tx();
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs]:
```suggestion
        let mut locked_utxos = self.locked_outpoints.lock();
        let tx = self
            .build_psbt(address, amount_sat_or_drain, fee, locked_utxos.clone())?
            .build_psbt(
                address.script_pubkey(),
                amount_sat_or_drain,
                fee,
                locked_utxos.clone(),
            )?
            .extract_tx();
```

File: crates/ln-dlc-node/src/ln_dlc_wallet.rs [hunk 8]
```diff
@@ -277,53 +277,57 @@ impl<S: TenTenOneStorage, N: Storage> dlc_manager::Wallet for LnDlcWallet<S, N>
...
+                        .expect("to be a valid address"),
+                    redeem_script: Default::default(),
+                    reserved: false,
+                },
+            })
             .collect::<Vec<_>>();
-        let selection = select_coins(amount, 20, &mut utxos)
+
+        // select enough utxos for our needs
+        let selected_local_utxos = select_coins(amount, 20, &mut utxos)
```
[the remark this answers is not in the document]
Comment (bonomat) [reply crates/ln-dlc-node/src/ln_dlc_wallet.rs:314]: This has been there from before 🤷‍♂️

File: crates/ln-dlc-node/src/ln_dlc_wallet.rs (hunk 1 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ln_dlc_wallet.rs:279]: Fair point. I move this logic into the wallet

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 2 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: done

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 3 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: done

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 5 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: done

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 6 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: done

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 7 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: done

File: crates/ln-dlc-node/src/ldk_node_wallet.rs [hunk 9]
```diff
@@ -205,6 +209,65 @@ where
...
+
+                Ok(selected_local_utxos
+                    .into_iter()
+                    .map(|utxo| utxo.utxo)
+                    .collect())
+            }
+        }
+    }
+
+    pub fn add_reserved_outpoint(&self, outpoint: OutPoint) {
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ldk_node_wallet.rs:237]: 🤔 it looks like this function isn't used anymore?

**Review by holzeis — APPROVED** [review]
LGTM 👍

File: crates/ln-dlc-node/src/ldk_node_wallet.rs (hunk 9 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ldk_node_wallet.rs]: good catch. Removed
