### PR TITLE
Fix: Close open position if dlc channel got force closed

### LINKED ISSUE #2106: Position is not set to closed if the underlying dlc channel got force closed.
As a result the coordinator tries to close the eventually expired position. Which is producing a significant amount of failed orders.

Screenshot 2024-02-27 at 14 10 35

see demo environment.

### PR DESCRIPTION
**Pull request by holzeis**
fixes #2106

### CODE REVIEW

File: coordinator/src/node/channel.rs [hunk 1]
```diff
@@ -38,7 +38,10 @@ impl Node {
                     match receiver.recv().await {
                         Ok(NodeEvent::DlcChannelEvent { dlc_channel_event }) => {
                             if let Err(e) = node.process_dlc_channel_event(dlc_channel_event) {
-                                tracing::error!("Failed to get connection. Error: {e:#}");
+                                tracing::error!(
+                                    ?dlc_channel_event,
+                                    "Failed to process dlc channel event. Error: {e:#}"
```
Comment (luckysori) [inline coordinator/src/node/channel.rs:43]: 🙃

```suggestion
                                    "Failed to process DLC channel event. Error: {e:#}"
```

File: coordinator/src/position/mod.rs [hunk 2]
```diff
@@ -1 +1,208 @@
...
+        dlc_channel_event: DlcChannelEvent,
+    ) -> Result<()> {
+        let mut conn = self.pool.get()?;
+
+        let protocol_id = match dlc_channel_event.get_reference_id() {
+            Some(reference_id) => reference_id,
+            None => {
+                bail!("Can't process dlc channel event without reference id. dlc_channel_event = {dlc_channel_event:?}");
+            }
+        };
```
Comment (luckysori) [inline coordinator/src/position/mod.rs:67]: 🔧 It's nicer to use `with_context()?`.

File: coordinator/src/position/mod.rs [hunk 3]
```diff
@@ -1 +1,208 @@
...
+                    to_secp_pk_30(trader_id),
+                    vec![PositionState::Open],
+                )? {
+                    Some(position) => position,
+                    None => return Ok(()),
+                };
+
+                let closing_price = match position.is_expired() {
+                    true => {
+                        let oracle = self.inner.oracles.first().context("Missing oracle")?;
```
Comment (luckysori) [inline coordinator/src/position/mod.rs:85]: ❓ How do we know that it is the first oracle?

File: coordinator/src/position/mod.rs [hunk 4]
```diff
@@ -1 +1,208 @@
...
+                    calculate_pnl(
+                        Decimal::from_f32(position.average_entry_price)
+                            .expect("to fit into decimal"),
+                        closing_price,
+                        position.quantity,
+                        trader_position_direction,
+                        initial_margin_long as u64,
+                        initial_margin_short as u64,
+                    )?
+                };
```
Comment (luckysori) [inline coordinator/src/position/mod.rs:155]: 📣 Surely we should get the PNL from the CET or the settle transaction if we get force-closed. Using this function won't be accurate.

File: mobile/native/src/position.rs [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+use crate::dlc::ChannelState;
+use crate::dlc::DlcChannel;
+use crate::dlc::SignedChannelState;
+use crate::event;
+use crate::event::subscriber::Subscriber;
+use crate::event::EventInternal;
+use crate::event::EventType;
+use trade::ContractSymbol;
+
+#[derive(Clone)]
```
Comment (luckysori) [inline mobile/native/src/position.rs:11]: 🔧 I guess it can be `Copy` 😆 But is this even needed?

Comment (holzeis) [reply mobile/native/src/position.rs:11]: Yes it's needed for the event hub.

File: coordinator/src/position/mod.rs (hunk 4 above)
Comment (holzeis) [reply coordinator/src/position/mod.rs:155]: We are only interested in the CET as for the settle transaction the position must have been closed.

How would you get the pnl of that position from the CET? Doesn't it include the reserve?

File: mobile/native/src/position.rs (hunk 5 above)
Comment (luckysori) [reply mobile/native/src/position.rs:11]: It's weird to have to `Clone` and empty type.

File: coordinator/src/position/mod.rs (hunk 4 above)
Comment (luckysori) [reply coordinator/src/position/mod.rs:155]: > We are only interested in the CET as for the settle transaction the position must have been closed.

That's not true. A settled channel (one without a DLC in it) can be force-closed too.

> How would you get the pnl of that position from the CET? Doesn't it include the reserve?

You would take the payout and subtract the reserve, which is now stored in the `dlc_channels` table.

What you are doing here is an approximation, which maybe is good enough, but I wasn't sure if that's what we wanted to do.

Comment (holzeis) [reply coordinator/src/position/mod.rs:155]: > You would take the payout and subtract the reserve, which is now stored in the `dlc_channels` table.
> 
> 
> 
> What you are doing here is an approximation, which maybe is good enough, but I wasn't sure if that's what we wanted to do.

I think that would work as well, but then the pnl would include on-chain fees. That wouldn't be consistent with the pnl calculation of other positions.

I was thinking to calculate the fees per channel differently. But I may be missing something.

Comment (luckysori) [reply coordinator/src/position/mod.rs:155]: > I think that would work as well, but then the pnl would include on-chain fees. That wouldn't be consistent with the pnl calculation of other positions.

The CET payouts are not reduced by on-chain fees. The on-chain fees come from the fee reserve. See https://github.com/p2pderivatives/rust-dlc/blob/883ad23f4c6467c90754ccce0b8820db10479f08/dlc/src/lib.rs#L572-L592.

File: mobile/native/src/position.rs (hunk 5 above)
Comment (holzeis) [reply mobile/native/src/position.rs:11]: Its because of this `subscribers: HashMap<EventType, Vec<Box<dyn Subscriber + 'static + Send + Sync>>>,` weirdness.

Comment (holzeis) [reply mobile/native/src/position.rs:11]: And I think this is needed because we keep the event hub in the storage state.

**Comment by holzeis** [comment]
@luckysori I changed the `trader_realized_pnl` calculation to use the cet payouts derived from the closed contract. It's much nicer now because we don't have to query the oracle again. Can you have another look?
