### PR TITLE
fix: Failed to create just in time channel due to disconnected peer

### LINKED ISSUE #330: Failed to create just-in-time channel due to disconnected node
If the coordinator is not connected to the payee upon creating a just-in-time channel it will panic with the following error message.

```
thread '<unnamed>' panicked at 'To open channel: Could not create channel with 02c8280854b03ab289fa0a76264b599413418092e242de26dcd1ec95679d8a4d4c due to Channel unavailable: Not connected to node: 02c8280854b03ab289fa0a76264b599413418092e242de26dcd1ec95679d8a4d4c', crates/ln-dlc-node/src/ln/event_handler.rs:492:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After this error occurs the coordinator is in a faulty state and has to be restarted.

### PR DESCRIPTION
**Pull request by holzeis**
The change also includes error handling in case the payment could not be forwarded and sets the HTLC to failed.

resolves #330

### CODE REVIEW

File: crates/ln-dlc-node/src/ln/event_handler.rs [hunk 1]
```diff
@@ -175,22 +174,38 @@ impl EventHandler {
                 fee_paid_msat,
                 ..
             } => {
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ln/event_handler.rs:176]: @luckysori: It appears that the outbound payment is never added to the the `self.outbound_payments`(At least I did not find any code for it). Hence the tests were not able to assert on a failed payment. I've adapted the code the code analogue to how we handle the Claimed Payment and insert the payment if `Vacant`. 

I suspected that this will also fix #328, but after a quick manual tests, it appears the issue still persists. Might be still something missing there. However, the tests are able to find the `outbound_payments` now.

File: crates/ln-dlc-node/src/ln/event_handler.rs [hunk 2]
```diff
@@ -480,16 +525,25 @@ impl EventHandler {
...
                             "Could not create channel with {} due to {e:?}",
                             target_node_id
                         )
-                    })
-                    .expect("To open channel");
+                    }) {
+                    Ok(temp_channel_id) => temp_channel_id,
+                    Err(_e) => {
+                        // todo: check why this tracing fails here.
+                        // tracing::warn!("Failed to open just in time channel. Error: {e:?}");
```
Comment (holzeis) [inline crates/ln-dlc-node/src/ln/event_handler.rs:540]: @luckysori: Do you know why this is failing? The event_handler panics at `backtrace::trace_unsynchronized`.

File: crates/ln-dlc-node/src/ln/event_handler.rs [hunk 3]
```diff
@@ -226,10 +242,26 @@ impl EventHandler {
...
+                    Entry::Occupied(mut e) => {
+                        let payment = e.get_mut();
+                        payment.status = HTLCStatus::Failed;
+                    }
+                    Entry::Vacant(e) => {
+                        e.insert(PaymentInfo {
+                            preimage: None,
+                            secret: None,
+                            status: HTLCStatus::Failed,
+                            // todo: decode amount from payment hash?
```
Comment (bonomat) [inline crates/ln-dlc-node/src/ln/event_handler.rs:260]: I don't think you can decode it from a hash? You'd need to retrieve it from somewhere.

File: crates/ln-dlc-node/src/ln/event_handler.rs (hunk 2 above)
Comment (bonomat) [reply crates/ln-dlc-node/src/ln/event_handler.rs:540]: commenting to follow this...

**Review by bonomat — APPROVED** [review]
Nice, this should hopefully get rid of the poison errors.

File: crates/ln-dlc-node/src/ln/event_handler.rs (hunk 3 above)
Comment (holzeis) [reply crates/ln-dlc-node/src/ln/event_handler.rs:260]: I think you are right.. otherwise that hash wouldn't be a good hash 😅

File: crates/ln-dlc-node/src/ln/event_handler.rs (hunk 1 above)
Comment (luckysori) [reply crates/ln-dlc-node/src/ln/event_handler.rs:176]: Good catch! I think we only ever tested manually with inbound payments 😨

File: crates/ln-dlc-node/src/ln/event_handler.rs (hunk 2 above)
Comment (luckysori) [reply crates/ln-dlc-node/src/ln/event_handler.rs:540]: Haha I've never come across this, I'll take a closer look.

File: crates/ln-dlc-node/src/node/invoice.rs [hunk 4]
```diff
@@ -113,13 +113,14 @@ impl Node {
...
+    pub fn create_intercept_scid(&self, target_node: PublicKey) -> Result<u64> {
         let intercept_scid = self.channel_manager.get_intercept_scid();
-        self.fake_channel_payments
+        let mut fake_channel_payment = self
+            .fake_channel_payments
             .lock()
-            .unwrap()
-            .insert(intercept_scid, target_node);
-        intercept_scid
+            .map_err(|e| anyhow!("{e:#}"))?;
```
Comment (luckysori) [inline crates/ln-dlc-node/src/node/invoice.rs:121]: 🤔 I think we should just `unwrap` or `expect` when dealing with locks. The reason why this panics is because the mutex was poisoned in the event handler that has all those _other_ unwraps. A mutex is poisoned if the guard is held and a panic occurs.

**Review by luckysori — COMMENTED** [review]
I will take it over so that we can merge it asap.

File: crates/ln-dlc-node/src/ln/event_handler.rs (hunk 2 above)
Comment (luckysori) [reply crates/ln-dlc-node/src/ln/event_handler.rs:540]: Could not reproduce in a test (where I caused a disconnect an saw the log being emitted).

File: crates/ln-dlc-node/src/ln/event_handler.rs [hunk 5]
```diff
@@ -69,7 +71,7 @@ impl EventHandler {
         }
     }
 
-    fn match_event(&self, event: Event) {
+    fn match_event(&self, event: Event) -> Result<()> {
```
[the remark this answers is not in the document]
Comment (luckysori) [reply crates/ln-dlc-node/src/ln/event_handler.rs:74]: I've split into multiple patches now.

File: crates/ln-dlc-node/src/ln/event_handler.rs [hunk 6]
```diff
@@ -175,22 +174,38 @@ impl EventHandler {
                 fee_paid_msat,
                 ..
             } => {
-                let mut payments = self.outbound_payments.lock().unwrap();
-                for (hash, payment) in payments.iter_mut() {
-                    if *hash == payment_hash {
+                let mut payments = self
+                    .outbound_payments
+                    .lock()
+                    .map_err(|e| anyhow!("{e:#}"))?;
```
[the remark this answers is not in the document]
Comment (klochowicz) [reply crates/ln-dlc-node/src/ln/event_handler.rs:180]: just chiming in: IMHO the best option would be to override the panic handler from Tokio to take down the whole application - if we're resilient to such restarts, we can *appear* really stable and will also spot problems much easier during development.
When an essential task crashes, there's nothing really we can do. Crashing and starting again seems much better than having a "zombie" app that appears to work, but doesn't do what it supposed to.
