### PR TITLE
fix: Add dedicated message if payment failed

### LINKED ISSUE #1121: "Send Payment Failure" with contradictory message
When trying to send sats on lightning from my 10101 wallet to an external wallet, it fails.

Can have several reasons BUT, the error message seems contradictory, here's a screenshot
IMG_6860

### PR DESCRIPTION
**Pull request by holzeis**
Note, this is just a quick patch for that scenario. We need to rework that dialog to wait for the payment to be successful or not, and not just depend whether we were able to submit the payment.

fixes #1121

### CODE REVIEW

File: mobile/lib/features/wallet/wallet_screen.dart [hunk 1]
```diff
@@ -84,7 +84,9 @@ class _WalletScreenState extends State<WalletScreen> {
                       Padding(
                         padding: const EdgeInsets.only(top: 20, left: 10, right: 10, bottom: 5),
                         child: Text(
-                            "Your Payment will be shown up in the wallet history automatically once it has been processed!",
+                            PendingPaymentState.failed == state
+                                ? "Failed to submit your payment. Please make sure that you have sufficient funds that the receiver is able to receive."
```
Comment (bonomat) [inline mobile/lib/features/wallet/wallet_screen.dart:88]: Is there an `and` missing?

```suggestion
                                ? "Failed to submit your payment. Please make sure that you have sufficient funds and that the receiver is able to receive."
```

**Review by bonomat — APPROVED** [review]

File: mobile/lib/features/wallet/wallet_screen.dart (hunk 1 above)
Comment (holzeis) [reply mobile/lib/features/wallet/wallet_screen.dart:88]: Maybe? I thought the sentence makes sense that way. You must have sufficient funds that the receiver is able to receive.

Maybe to complicated? To be honest I haven't spent much time on it, but figured that's such an easy thing ticket, let's fix it very quickly, knowing that we have to rework that entire screen anyways 🙂

Comment (bonomat) [reply mobile/lib/features/wallet/wallet_screen.dart:88]: My english is not the yellow from the egg. 
I think it makes sense as you had it.

**Comment by SXBT69** [comment]
Thx!
